if(NOT DEFINED WIO_EXE OR WIO_EXE STREQUAL "")
    message(FATAL_ERROR "WIO_EXE was not provided.")
endif()
if(NOT DEFINED WIO_SCRATCH_DIR OR WIO_SCRATCH_DIR STREQUAL "")
    message(FATAL_ERROR "WIO_SCRATCH_DIR was not provided.")
endif()

set(project_name "LifecycleApp")
set(project_root "${WIO_SCRATCH_DIR}/${project_name}")
set(package_parent "${project_root}/release")
set(package_root "${package_parent}/lifecycleapp")

file(REMOVE_RECURSE "${WIO_SCRATCH_DIR}")
file(MAKE_DIRECTORY "${WIO_SCRATCH_DIR}")

execute_process(
    COMMAND "${WIO_EXE}" --self-hosted-info
    WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
    RESULT_VARIABLE selfhost_result
    OUTPUT_VARIABLE selfhost_stdout
    ERROR_VARIABLE selfhost_stderr
)
set(selfhost_output "${selfhost_stdout}${selfhost_stderr}")
if(NOT selfhost_result EQUAL 0 OR
   NOT selfhost_output MATCHES "Argonaut-Wio bootstrap")
    message(FATAL_ERROR
        "The project lifecycle did not enter the self-hosted CLI.\n${selfhost_output}"
    )
endif()

execute_process(
    COMMAND "${WIO_EXE}" project new "${project_name}"
            --output-dir "${WIO_SCRATCH_DIR}" --template wio-app
    WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
    RESULT_VARIABLE new_result
    OUTPUT_VARIABLE new_stdout
    ERROR_VARIABLE new_stderr
)
if(NOT new_result EQUAL 0)
    message(FATAL_ERROR
        "Lifecycle smoke failed during project creation.\n${new_stdout}${new_stderr}"
    )
endif()
file(READ "${project_root}/README.md" generated_readme)
if(NOT generated_readme MATCHES "Generated by the self-hosted")
    message(FATAL_ERROR
        "Project creation did not use the Wio-owned implementation.\n${generated_readme}"
    )
endif()

file(MAKE_DIRECTORY "${project_root}/tests" "${project_root}/assets")
file(WRITE "${project_root}/tests/lifecycle.wio"
    "use std::console;\n\n"
    "fn Entry() -> i32 {\n"
    "    std::console::Print(\"project-test-ok\");\n"
    "    return 0;\n"
    "}\n"
)
file(WRITE "${project_root}/assets/example.txt" "packaged-asset-ok\n")

execute_process(
    COMMAND "${WIO_EXE}" project test --list --filter "lifecycle"
    WORKING_DIRECTORY "${project_root}"
    RESULT_VARIABLE list_result
    OUTPUT_VARIABLE list_stdout
    ERROR_VARIABLE list_stderr
)
set(list_output "${list_stdout}${list_stderr}")
if(NOT list_result EQUAL 0 OR
   NOT list_output MATCHES "tests/lifecycle\\.wio" OR
   NOT list_output MATCHES "1 project test\\(s\\) matched")
    message(FATAL_ERROR "Project test listing failed.\n${list_output}")
endif()

execute_process(
    COMMAND "${WIO_EXE}" project test --filter "lifecycle"
    WORKING_DIRECTORY "${project_root}"
    RESULT_VARIABLE test_result
    OUTPUT_VARIABLE test_stdout
    ERROR_VARIABLE test_stderr
)
set(test_output "${test_stdout}${test_stderr}")
if(NOT test_result EQUAL 0 OR
   NOT test_output MATCHES "project-test-ok" OR
   NOT test_output MATCHES "1/1 project test\\(s\\) passed")
    message(FATAL_ERROR "Project test execution failed.\n${test_output}")
endif()

execute_process(
    COMMAND "${WIO_EXE}" project test --no-build --filter "lifecycle"
    WORKING_DIRECTORY "${project_root}"
    RESULT_VARIABLE no_build_test_result
    OUTPUT_VARIABLE no_build_test_stdout
    ERROR_VARIABLE no_build_test_stderr
)
if(NOT no_build_test_result EQUAL 0)
    message(FATAL_ERROR
        "Prebuilt project test execution failed.\n"
        "${no_build_test_stdout}${no_build_test_stderr}"
    )
endif()

execute_process(
    COMMAND "${WIO_EXE}" project package
            --output-dir "${package_parent}" --clean
    WORKING_DIRECTORY "${project_root}"
    RESULT_VARIABLE package_result
    OUTPUT_VARIABLE package_stdout
    ERROR_VARIABLE package_stderr
)
if(NOT package_result EQUAL 0)
    message(FATAL_ERROR
        "Project packaging failed.\n${package_stdout}${package_stderr}"
    )
endif()

if(WIN32)
    set(packaged_executable "${package_root}/bin/lifecycleapp.exe")
    set(package_launcher "${package_root}/run.cmd")
else()
    set(packaged_executable "${package_root}/bin/lifecycleapp")
    set(package_launcher "${package_root}/run.sh")
endif()
foreach(required_path IN ITEMS
        "${packaged_executable}"
        "${package_launcher}"
        "${package_root}/assets/example.txt"
        "${package_root}/wio-package.json")
    if(NOT EXISTS "${required_path}")
        message(FATAL_ERROR "Project package is missing: ${required_path}")
    endif()
endforeach()

file(READ "${package_root}/wio-package.json" package_metadata)
if(NOT package_metadata MATCHES "\"name\": \"LifecycleApp\"" OR
   NOT package_metadata MATCHES "\"target\": \"exe\"")
    message(FATAL_ERROR "Project package metadata is incomplete.\n${package_metadata}")
endif()

if(WIN32)
    execute_process(
        COMMAND cmd /c "${package_launcher}"
        WORKING_DIRECTORY "${package_root}"
        RESULT_VARIABLE launcher_result
        OUTPUT_VARIABLE launcher_stdout
        ERROR_VARIABLE launcher_stderr
    )
else()
    execute_process(
        COMMAND "${package_launcher}"
        WORKING_DIRECTORY "${package_root}"
        RESULT_VARIABLE launcher_result
        OUTPUT_VARIABLE launcher_stdout
        ERROR_VARIABLE launcher_stderr
    )
endif()
set(launcher_output "${launcher_stdout}${launcher_stderr}")
if(NOT launcher_result EQUAL 0 OR
   NOT launcher_output MATCHES "Hello from a plain Wio application")
    message(FATAL_ERROR "Packaged project launcher failed.\n${launcher_output}")
endif()

message(STATUS "Project test/package lifecycle smoke succeeded for ${project_root}")
